# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b938b801f904fa3740342132f57c70ebc9c5ae0cc5cb1c8ebbf0d13a54d8cb3cde80101f638ed72a14271443d2858f072eb44b13bc7c930143b80ba8d32500f

test:
  secret_key_base: d7f25d2e98aded993db1da4dc91776e5ba989c8999292159aeb7f292e1737930b67e92a7bd8901c00ceacfb68620dd360a973817c59a0f75406fc9633560b222

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
